# SPDX-FileCopyrightText: 2024 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure freescout paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  with_items:
    - "{{ freescout_base_path }}"
    - "{{ freescout_data_path }}"
    - "{{ freescout_logs_path }}"
    - "{{ freescout_modules_path }}"

- name: Ensure freescout support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ freescout_base_path }}/{{ item }}"
    mode: 0640
  with_items:
    - env
    - labels

- name: Ensure freescout container image is pulled
  community.docker.docker_image:
    name: "{{ freescout_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ freescout_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else freescout_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure freescout container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ freescout_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure freescout systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/freescout.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ freescout_identifier }}.service"
    mode: 0644
