# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform FreeScout installation tasks
  when: freescout_enabled | bool
  tags:
    - setup-all
    - setup-freescout
    - install-all
    - install-freescout
  block:
    - name: Validate FreeScout configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install FreeScout
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform FreeScout uninstallation tasks
  when: not freescout_enabled | bool
  tags:
    - setup-all
    - setup-freescout
  block:
    - name: Uninstall FreeScout
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
