# SPDX-FileCopyrightText: 2024 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- block:
    - when: freescout_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: freescout_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-freescout
    - install-all
    - install-freescout

- block:
    - when: not freescout_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-freescout
