# SPDX-FileCopyrightText: 2024 Nikita Chernyi
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of FreeScout systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ freescout_identifier }}.service"
  register: freescout_service_stat

- name: Uninstall FreeScout systemd services and files
  when: freescout_service_stat.stat.exists | bool
  block:
    - name: Ensure FreeScout systemd service is stopped
      ansible.builtin.service:
        name: "{{ freescout_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure FreeScout systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ freescout_identifier }}.service"
        state: absent

    - name: Ensure FreeScout container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ freescout_container_network }}"
        state: absent

    - name: Ensure FreeScout container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ freescout_container_network }}
      register: network_deletion_result
      changed_when: freescout_container_network in network_deletion_result.stdout

    - name: Ensure FreeScout path does not exist
      ansible.builtin.file:
        path: "{{ freescout_base_path }}"
        state: absent
