# SPDX-FileCopyrightText: 2024 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of freescout systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ freescout_identifier }}.service"
  register: freescout_service_stat

- when: freescout_service_stat.stat.exists | bool
  block:
    - name: Ensure freescout systemd service is stopped
      ansible.builtin.service:
        name: "{{ freescout_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure freescout systemd service does not exists
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ freescout_identifier }}.service"
        state: absent

    - name: Ensure freescout path doesn't exist
      ansible.builtin.file:
        path: "{{ freescout_base_path }}"
        state: absent
