# SPDX-FileCopyrightText: 2024 Nikita Chernyi
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of FreeScout systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ freescout_identifier }}.service"
  register: freescout_service_stat

- name: Uninstall FreeScout systemd services and files
  when: freescout_service_stat.stat.exists | bool
  block:
    - name: Ensure FreeScout systemd service is stopped
      ansible.builtin.service:
        name: "{{ freescout_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure FreeScout systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ freescout_identifier }}.service"
        state: absent

    - name: Ensure FreeScout support files do not exist
      ansible.builtin.file:
        path: "{{ freescout_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels

    - name: Ensure FreeScout local data path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ freescout_data_path }}"
      register: freescout_data_path_deletion_result
      changed_when: freescout_data_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure FreeScout local logs path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ freescout_logs_path }}"
      register: freescout_logs_path_deletion_result
      changed_when: freescout_logs_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure FreeScout local modules path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ freescout_modules_path }}"
      register: freescout_modules_path_deletion_result
      changed_when: freescout_modules_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure FreeScout base path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ freescout_base_path }}"
      register: freescout_base_path_deletion_result
      changed_when: freescout_base_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure FreeScout container network does not exist
      when: freescout_container_network_deletion_enabled
      block:
        - name: Ensure FreeScout container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ freescout_container_network }}"
            state: absent
          register: freescout_network_deletion_result

        - name: Ensure FreeScout container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ freescout_container_network }}
          register: freescout_network_deletion_result
          changed_when: freescout_container_network in freescout_network_deletion_result.stdout

- name: Check existence of FreeScout local data path
  ansible.builtin.stat:
    path: "{{ freescout_data_path }}"
  register: freescout_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Inject the message about the remaining FreeScout local data path
  when: freescout_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local FreeScout instance has been removed, some old data remains in `" + freescout_data_path + "`. Feel free to delete it."
        ]
      }}

- name: Check existence of FreeScout local logs path
  ansible.builtin.stat:
    path: "{{ freescout_logs_path }}"
  register: freescout_logs_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Inject the message about the remaining FreeScout local log data path
  when: freescout_logs_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local FreeScout instance has been removed, some old log data remains in `" + freescout_logs_path + "`. Feel free to delete it."
        ]
      }}

- name: Check existence of FreeScout local modules path
  ansible.builtin.stat:
    path: "{{ freescout_modules_path }}"
  register: freescout_modules_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Inject the message about the remaining FreeScout modules data path
  when: freescout_modules_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local FreeScout instance has been removed, some modules data remains in `" + freescout_modules_path + "`. Feel free to delete it."
        ]
      }}
