# SPDX-FileCopyrightText: 2024 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Fail if required freescout settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - freescout_identifier
    - freescout_hostname
    - freescout_admin_email
    - freescout_admin_password
    - freescout_path_prefix
    - freescout_container_network
    - freescout_database_hostname
    - freescout_database_password

- when: freescout_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required freescout Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - freescout_container_labels_traefik_hostname
        - freescout_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `freescout_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if freescout_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          freescout_container_labels_traefik_path_prefix (`{{ freescout_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/freescout`).
      when: "freescout_container_labels_traefik_path_prefix != '/' and freescout_container_labels_traefik_path_prefix[-1] == '/'"
